//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetUserByEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public byte[] ProfilePicture { get; set; }
        public Nullable<System.DateTime> RegisteredOn { get; set; }
        public Nullable<System.DateTime> LastTimeLoggedIn { get; set; }
        public int Age { get; set; }
        public bool IsDeleted { get; set; }
    }
}
